# Generated by Django 3.1.7 on 2021-04-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='previousOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('orderDateTime', models.DateTimeField(auto_now_add=True)),
                ('hotelName', models.CharField(max_length=50)),
                ('cityName', models.CharField(max_length=50)),
                ('bookingDate', models.DateField()),
                ('bookingTime', models.TimeField()),
            ],
        ),
    ]
