# Generated by Django 3.1.7 on 2021-04-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousorders',
            old_name='bookingDate',
            new_name='bookingdate',
        ),
        migrations.RenameField(
            model_name='previousorders',
            old_name='bookingTime',
            new_name='bookingtime',
        ),
        migrations.RenameField(
            model_name='previousorders',
            old_name='cityName',
            new_name='cityname',
        ),
        migrations.RenameField(
            model_name='previousorders',
            old_name='hotelName',
            new_name='hotelname',
        ),
        migrations.RenameField(
            model_name='previousorders',
            old_name='orderDateTime',
            new_name='ordertime',
        ),
    ]
